config/routes.rb
Rails.application.routes.draw do
  devise_for :ssh_details, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    resources :addresses
  end

  root to: 'home#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user

  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zipcode, presence: true
  validates :zipcode, numericality: { only_integer: true }
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ssh_detail.rb
class SshDetail < ActiveRecord::Base
  validates :ssh_username, presence: true, uniqueness: true
  validates :ssh_password, presence: true
  validates :ip_address, presence: true, uniqueness: true
  validates :port, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses

  validates :name, presence: true

  def is_admin?
    # self.role == 'admin'
    true
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :show, :destroy]
  before_action :set_user, only: [:new, :edit, :index]

  def index
    @addresses = @user.addresses
  end

  def new
    @address = @user.addresses.build
  end

  def create
    @address = Address.create(address_params)
    @address.user = current_user
    if @address.save
      flash[:notice] = "Address Succfully created."
      redirect_to user_addresses_path(current_user)
    else
      flash[:alert] = @address.errors.full_messages
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      flash[:notice] = "Address Succfully updated."
      redirect_to user_addresses_path(current_user)
    else
      flash[:alert] = @address.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    if @address.delete
      flash[:notice] = "Address successfully deleted."
    else
      flash[:alert] = "Can not delete address."
    end
    redirect_to user_addresses_path(current_user)
  end

  private
  def set_address
    @address = Address.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def address_params
    params.require(:address).permit(:address1, :address2, :city, :state, :country, :zipcode)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin_user!
    redirect_to '/' and return if user_signed_in? && !current_user.is_admin?
    authenticate_user!
  end

  def current_admin_user
    return nil if user_signed_in? && !current_user.is_admin?
    current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<div class="field">
  <%= f.label :address1 %><br />
  <%= f.text_field :address1, autofocus: true %>
</div>

<div class="field">
  <%= f.label :address2 %><br />
  <%= f.text_field :address2, autofocus: true %>
</div>

<div class="field">
  <%= f.label :city %><br />
  <%= f.text_field :city %>
</div>

<div class="field">
  <%= f.label :state %><br />
  <%= f.text_field :state %>
</div>

<div class="field">
  <%= f.label :country %><br />
  <%= f.text_field :country %>
</div>

<div class="field">
  <%= f.label :zipcode %><br />
  <%= f.text_field :zipcode %>
</div>

app/views/addresses/_index.html.erb
<div class="container">
  <h2>User Address</h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Country</th>
          <th>ZiCode</th>
          <th>View</th>
        </tr>
      </thead>
      <tbody>
        <% addresses.each do |address|%>
          <tr>
            <td><%=address.id%></td>
            <td><%=address.address1%> <%=address.address2%></td>
            <td><%=address.city%></td>
            <td><%=address.state%></td>
            <td><%=address.country%></td>
            <td><%=address.zipcode%></td>
            <td><%= link_to 'View', admin_address_path %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/addresses/edit.html.erb
<%= form_for [@user, @address]  do |f| %>

  <%= render partial: '/addresses/form', locals: {f: f} %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/addresses/index.html.erb
<div class="container">
  <h2>User Address<%= link_to 'New Address', new_user_address_path, class: 'btn btn-default pull-right' %></h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Country</th>
          <th>ZiCode</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @addresses.each do |address|%>
          <tr>
            <td><%=address.id%></td>
            <td><%=address.address1%> <%=address.address2%></td>
            <td><%=address.city%></td>
            <td><%=address.state%></td>
            <td><%=address.country%></td>
            <td><%=address.zipcode%></td>
            <td><%= link_to 'Edit', edit_user_address_path(address.user, address) %></td>
            <td><%= link_to 'Delete', user_address_path(address.user, address), method: :delete, confirm: "Are You sure you want to delete this address?" %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/addresses/new.html.erb
<%= form_for [@user, @address]  do |f| %>

  <%= render partial: '/addresses/form', locals: {f: f} %>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render partial: '/users/user_detail' if user_signed_in?%>

app/views/layouts/_header.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <ul class="nav nav-tabs">
    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
  </ul>
<% else %>
  <ul class="nav nav-tabs">
    <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
    <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
  </ul>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminRails</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text pull-right">
    <div class="container">
      <%= render partial: '/layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_user_detail.html.erb
<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= current_user.name %></dd>
  <dt>Email</dt>
  <dd><%= current_user.email %></dd>
  <%= link_to 'Address List', user_addresses_path(current_user), class: 'btn btn-default' %>
</dl>